// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Channel = (function(_super) {

    __extends(Channel, _super);

    function Channel() {
      return Channel.__super__.constructor.apply(this, arguments);
    }

    return Channel;

  })(Backbone.Model);

  window.Channels = (function(_super) {

    __extends(Channels, _super);

    function Channels() {
      return Channels.__super__.constructor.apply(this, arguments);
    }

    Channels.prototype.model = Channel;

    Channels.prototype.url = "apiV1/channel";

    return Channels;

  })(Backbone.Collection);

}).call(this);
