// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.SettingsSection = (function(_super) {

    __extends(SettingsSection, _super);

    function SettingsSection() {
      return SettingsSection.__super__.constructor.apply(this, arguments);
    }

    SettingsSection.prototype.urlRoot = '/apiV1/config';

    SettingsSection.prototype.idAttribute = 'sectionName';

    SettingsSection.prototype.relations = [
      {
        type: Backbone.HasMany,
        key: 'settings',
        relatedModel: 'window.Setting',
        collectionType: 'window.Settings'
      }
    ];

    SettingsSection.prototype.parse = function(response) {
      return response;
    };

    return SettingsSection;

  })(Backbone.RelationalModel);

  window.SettingsSection.setup();

  window.Setting = (function(_super) {

    __extends(Setting, _super);

    function Setting() {
      return Setting.__super__.constructor.apply(this, arguments);
    }

    Setting.prototype.idAttribute = 'key';

    Setting.prototype.relations = [
      {
        type: Backbone.HasOne,
        key: 'section',
        relatedModel: 'window.SettingsSection',
        collectionType: 'window.SettingsSections'
      }
    ];

    return Setting;

  })(Backbone.RelationalModel);

  window.Setting.setup();

  window.Settings = (function(_super) {

    __extends(Settings, _super);

    function Settings() {
      return Settings.__super__.constructor.apply(this, arguments);
    }

    Settings.prototype.model = Setting;

    return Settings;

  })(Backbone.Collection);

  window.SettingsSections = (function(_super) {

    __extends(SettingsSections, _super);

    function SettingsSections() {
      return SettingsSections.__super__.constructor.apply(this, arguments);
    }

    SettingsSections.prototype.model = SettingsSection;

    SettingsSections.prototype.url = 'apiV1/config';

    return SettingsSections;

  })(Backbone.Collection);

}).call(this);
