// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ChannellistitemView = (function(_super) {

    __extends(ChannellistitemView, _super);

    function ChannellistitemView() {
      return ChannellistitemView.__super__.constructor.apply(this, arguments);
    }

    ChannellistitemView.prototype.render = function() {
      $(this.el).html(this.template());
      return this;
    };

    return ChannellistitemView;

  })(Backbone.View);

}).call(this);
