// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ChannellistView = (function(_super) {

    __extends(ChannellistView, _super);

    function ChannellistView() {
      return ChannellistView.__super__.constructor.apply(this, arguments);
    }

    ChannellistView.prototype.tagName = 'ul';

    ChannellistView.prototype.className = 'nav nav-list';

    ChannellistView.prototype.id = 'channelnavigation';

    ChannellistView.prototype.initialize = function() {
      return this.model.bind("all", function() {
        return this.render();
      }, this);
    };

    ChannellistView.prototype.render = function(eventName) {
      var _this = this;
      $(this.el).children().remove();
      _.each(this.model.models, function(channel) {
        return $(_this.el).append(_this.template(channel.toJSON()));
      });
      return this;
    };

    return ChannellistView;

  })(Backbone.View);

}).call(this);
