// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.SettingslistView = (function(_super) {

    __extends(SettingslistView, _super);

    function SettingslistView() {
      return SettingslistView.__super__.constructor.apply(this, arguments);
    }

    console.log('SettingslistView loaded');

    SettingslistView.prototype.tagName = 'ul';

    SettingslistView.prototype.className = 'nav nav-list';

    SettingslistView.prototype.id = 'settingsnavigation';

    SettingslistView.prototype.initialize = function() {
      return this.model.bind("all", function() {
        return this.render();
      }, this);
    };

    SettingslistView.prototype.render = function(eventName) {
      var _this = this;
      $(this.el).html('');
      _.each(this.model.models, function(setting) {
        return $(_this.el).append(_this.template(setting.toJSON()));
      });
      return this;
    };

    return SettingslistView;

  })(Backbone.View);

}).call(this);
