// Generated by CoffeeScript 1.3.3
(function() {

  window.TopnavView = Backbone.View.extend({
    initialize: function() {
      return this.activeSection = 'Channels';
    },
    render: function() {
      $(this.el).html(this.template());
      $('#topnav' + this.activeSection, this.el).addClass('active');
      return this;
    }
  });

}).call(this);
